Repository TheCodeMonks/Notzz-App, pull requests merged in 2020-10, with the labels that each got.

#8 Refactoring UI & Fixed Backstack Bug #6
  .idea/compiler.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/thecodemonks/org/nottzapp/UI/AddNotes/AddNotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/UI/AddNotes/Notes/ViewModelProviders/ViewModelProviderFactory.kt
  app/src/main/java/thecodemonks/org/nottzapp/UI/Notes/NotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/UI/Notes/ViewModelProviders/ViewModelProviderFactory.kt
  app/src/main/java/thecodemonks/org/nottzapp/UI/Notes/ViewModels/NotesViewModel.kt
  app/src/main/java/thecodemonks/org/nottzapp/UI/NotesDetails/NotesDetailsFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/adapter/NotesAdapter.kt
  app/src/main/java/thecodemonks/org/nottzapp/app/MainActivity.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDao.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDatabase.kt
  app/src/main/java/thecodemonks/org/nottzapp/model/Notes.kt
  app/src/main/java/thecodemonks/org/nottzapp/repo/NotesRepo.kt
  app/src/main/res/font/montserrat.xml
  app/src/main/res/font/montserrat_bold.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_notes_fragment.xml
  app/src/main/res/layout/fragment_notes_details.xml
  app/src/main/res/layout/item_post_notes.xml
  app/src/main/res/layout/notes_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/font_certs.xml
  app/src/main/res/values/preloaded_fonts.xml
  app/src/main/res/values/strings.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: UI Revamp, bug

#9 Update Card & Logo
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/nottzlogo.png
  screenshots/AddNotes.png
  screenshots/NOTZZ APP CARD.jpg
  screenshots/Notzzapp.png
Labels: documentation

#10 Localization-friendly, small code and layout improvements
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  app/src/main/java/thecodemonks/org/nottzapp/UI/Notes/ViewModelProviders/ViewModelProviderFactory.kt
  app/src/main/java/thecodemonks/org/nottzapp/adapter/NotesAdapter.kt
  app/src/main/java/thecodemonks/org/nottzapp/app/MainActivity.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDao.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDatabase.kt
  app/src/main/java/thecodemonks/org/nottzapp/model/Notes.kt
  app/src/main/java/thecodemonks/org/nottzapp/repo/NotesRepo.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/add/AddNotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/details/NotesDetailsFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesViewModel.kt
  app/src/main/java/thecodemonks/org/nottzapp/utils/factory/ViewModelProviderFactory.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_notes_fragment.xml
  app/src/main/res/layout/fragment_notes_details.xml
  app/src/main/res/layout/item_post_notes.xml
  app/src/main/res/layout/notes_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Improvements

#11 Localization-friendly, small code and layout improvements
  .idea/codeStyles/Project.xml
  .idea/gradle.xml
  app/src/main/java/thecodemonks/org/nottzapp/UI/Notes/ViewModelProviders/ViewModelProviderFactory.kt
  app/src/main/java/thecodemonks/org/nottzapp/adapter/NotesAdapter.kt
  app/src/main/java/thecodemonks/org/nottzapp/app/MainActivity.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDao.kt
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDatabase.kt
  app/src/main/java/thecodemonks/org/nottzapp/model/Notes.kt
  app/src/main/java/thecodemonks/org/nottzapp/repo/NotesRepo.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/add/AddNotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/details/NotesDetailsFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesViewModel.kt
  app/src/main/java/thecodemonks/org/nottzapp/utils/factory/ViewModelProviderFactory.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_notes_fragment.xml
  app/src/main/res/layout/fragment_notes_details.xml
  app/src/main/res/layout/item_post_notes.xml
  app/src/main/res/layout/notes_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Improvements

#12 Remove editText bottom bar
  app/src/main/res/layout/add_notes_fragment.xml
  app/src/main/res/layout/fragment_notes_details.xml
Labels: Improvements

#22 Add Delete & Share Note Feature
  .idea/codeStyles/Project.xml
  app/src/main/java/thecodemonks/org/nottzapp/app/MainActivity.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/details/NotesDetailsFragment.kt
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_notes_details.xml
  app/src/main/res/layout/item_post_notes.xml
  app/src/main/res/menu/share_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, hacktoberfest-accepted

#24 Fix Scrollable note description & Refactor Code
  app/src/main/java/thecodemonks/org/nottzapp/db/NotesDao.kt
  app/src/main/java/thecodemonks/org/nottzapp/model/Notes.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesFragment.kt
  app/src/main/java/thecodemonks/org/nottzapp/ui/notes/NotesViewModel.kt
  app/src/main/res/layout/add_notes_fragment.xml
  app/src/main/res/layout/fragment_notes_details.xml
  app/src/main/res/values/styles.xml
Labels: bug, hacktoberfest-accepted
